//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct hostent {
    char *e0;
    char **e1;
    int32_t e2;
    int32_t e3;
    char **e4;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _fini(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _start(int32_t i_a1, int32_t i_a2);
int32_t callapi(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t display(int32_t i_a1);
int32_t function_108b0(char *s1, char *s2);
int32_t function_108bc(char *nptr, char **endptr, int32_t base);
int32_t function_108c8(char *format, ...);
int32_t *function_108d4(int32_t *ptr, int32_t size);
int32_t *function_108e0(int32_t *s, int32_t c);
int32_t function_108ec(char *s);
int32_t *function_108f8(int32_t size);
int32_t function_10904(int32_t main2, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
char *function_10910(int32_t errnum);
void function_1091c(void);
int16_t **function_10928(void);
int32_t function_10934(char *s);
char *function_10940(char *s, int32_t c);
int32_t function_1094c(struct _IO_FILE *stream, char *format, ...);
int32_t *function_10958(void);
int32_t function_10964(int32_t domain, int32_t type, int32_t protocol);
struct hostent *function_10970(char *name);
void function_1097c(void);
int32_t function_10988(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10994(int32_t fd);
int32_t function_109a0(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_109ac(int32_t fd, struct sockaddr *addr, int32_t len);
int32_t function_10b4c(void);
int32_t function_10b80(int32_t i_a1);
int32_t function_10b8c(void);
int32_t function_10bb0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10c0c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_10c18(void);
int32_t function_10c1c(int32_t i_a1);
int32_t function_44c6e0(void);
int32_t function_44c718(void);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

char *p_g1;                   // 0x1110c
int32_t i_g2 = 0x10c19;       // 0x21f0c
int32_t i_g3 = 0;             // 0x22064
struct _IO_FILE *p_g4 = NULL; // 0x22070
int32_t i_g5 = 0;             // 0x22078
int32_t i_g6;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());
int32_t *__rawmemchr(int32_t *p_a1, int32_t i_a2);

// ------------------------ Functions -------------------------

// Address range: 0x10890 - 0x1089c
int32_t _init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10890
    return function_10b8c();
}

// Address range: 0x108b0 - 0x108bc
int32_t function_108b0(char *s1, char *s2) {
    // 0x108b0
    return strcmp(s1, s2);
}

// Address range: 0x108bc - 0x108c8
int32_t function_108bc(char *nptr, char **endptr, int32_t base) {
    // 0x108bc
    return strtol(nptr, endptr, base);
}

// Address range: 0x108c8 - 0x108d4
int32_t function_108c8(char *format, ...) {
    // 0x108c8
    return printf(format);
}

// Address range: 0x108d4 - 0x108e0
int32_t *function_108d4(int32_t *ptr, int32_t size) {
    // 0x108d4
    return realloc(ptr, size);
}

// Address range: 0x108e0 - 0x108ec
int32_t *function_108e0(int32_t *s, int32_t c) {
    // 0x108e0
    return __rawmemchr(s, c);
}

// Address range: 0x108ec - 0x108f8
int32_t function_108ec(char *s) {
    // 0x108ec
    return puts(s);
}

// Address range: 0x108f8 - 0x10904
int32_t *function_108f8(int32_t size) {
    // 0x108f8
    return malloc(size);
}

// Address range: 0x10904 - 0x10910
int32_t function_10904(int32_t main2, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10904
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10910 - 0x1091c
char *function_10910(int32_t errnum) {
    // 0x10910
    return strerror(errnum);
}

// Address range: 0x1091c - 0x10928
void function_1091c(void) {
    // 0x1091c
    __gmon_start__();
}

// Address range: 0x10928 - 0x10934
int16_t **function_10928(void) {
    // 0x10928
    return __ctype_b_loc();
}

// Address range: 0x10934 - 0x10940
int32_t function_10934(char *s) {
    // 0x10934
    return strlen(s);
}

// Address range: 0x10940 - 0x1094c
char *function_10940(char *s, int32_t c) {
    // 0x10940
    return strchr(s, c);
}

// Address range: 0x1094c - 0x10958
int32_t function_1094c(struct _IO_FILE *stream, char *format, ...) {
    // 0x1094c
    return fprintf(stream, format);
}

// Address range: 0x10958 - 0x10964
int32_t *function_10958(void) {
    // 0x10958
    return __errno_location();
}

// Address range: 0x10964 - 0x10970
int32_t function_10964(int32_t domain, int32_t type, int32_t protocol) {
    // 0x10964
    return socket(domain, type, protocol);
}

// Address range: 0x10970 - 0x1097c
struct hostent *function_10970(char *name) {
    // 0x10970
    return gethostbyname(name);
}

// Address range: 0x1097c - 0x10988
void function_1097c(void) {
    // 0x1097c
    abort();
}

// Address range: 0x10988 - 0x10994
int32_t function_10988(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x10988
    return recv(fd, buf, n, flags);
}

// Address range: 0x10994 - 0x109a0
int32_t function_10994(int32_t fd) {
    // 0x10994
    return close(fd);
}

// Address range: 0x109a0 - 0x109ac
int32_t function_109a0(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x109a0
    return send(fd, buf, n, flags);
}

// Address range: 0x109ac - 0x109b8
int32_t function_109ac(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x109ac
    return connect(fd, addr, len);
}

// Address range: 0x109b8 - 0x10b4c
int main(int argc, char **argv) {
    // 0x109b8
    if (argc < 2) {
        // 0x10ae0
        return callapi((int32_t) "summary", (int32_t) "127.0.0.1", 4028);
    }
    int32_t i_v1 = (int32_t)argv;
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x109c4
    char *p_v3 = (char *)i_v2;             // 0x109d0
    char i_v4;                             // 0x10a6c
    if (*p_v3 == 45) {
        // 0x10a6c
        i_v4 = *(char *)(i_v2 + 1);
        switch (i_v4) {
        case 63: {
            // 0x10a78
            if (*(char *)(i_v2 + 2) == 0) {
                // 0x10b04
                fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n",
                        (char *)0x11b4);
                return 1;
            }
            goto lab_0x10a84;
        }
        case 104: {
            // 0x10af8
            if (*(char *)(i_v2 + 2) == 0) {
                // 0x10b04
            }
            goto lab_0x109dc;
        }
        default: {
            goto lab_0x10a84;
        }
        }
    } else {
        goto lab_0x109dc;
    }
lab_0x109dc:;
    int32_t i_v5 = 1; // 0x109f0
    if (strcmp(p_v3, "--help") == 0) {
        // 0x10b04
        fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n", (char *)0x11b4);
        return 1;
    }
    goto lab_0x109f8;
lab_0x10a84:
    // 0x10a84
    if (strcmp(p_v3, "--help") == 0) {
        // 0x10b04
        fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n", (char *)0x11b4);
        return 1;
    }
    // 0x10a9c
    i_v5 = 1;
    if (i_v4 == 111) {
        // 0x10aa4
        i_v5 = 1;
        if (*(char *)(i_v2 + 2) == 0) {
            // 0x10ab0
            i_g5 = 1;
            i_v5 = 2;
            if (argc == 2) {
                // 0x10ae0
                return callapi((int32_t) "summary", (int32_t) "127.0.0.1",
                               4028);
            }
        }
    }
    goto lab_0x109f8;
lab_0x109f8:;
    int32_t i_v6 = 4 * i_v5 + i_v1;                  // 0x109f8
    int32_t i_v7 = function_10c1c(*(int32_t *)i_v6); // 0x10a00
    int32_t i_v8 = *(char *)i_v7 == 0 ? (int32_t) "summary" : i_v7;
    if (i_v5 + 1 >= argc) {
        // 0x10ae0
        return callapi(i_v8, (int32_t) "127.0.0.1", 4028);
    }
    int32_t i_v9 = function_10c1c(*(int32_t *)(i_v6 + 4)); // 0x10a34
    int32_t i_v10 = *(char *)i_v9 == 0 ? (int32_t) "127.0.0.1" : i_v9;
    if (i_v5 + 2 >= argc) {
        // 0x10ae0
        return callapi(i_v8, i_v10, 4028);
    }
    char *p_v11 = (char *)function_10c1c(*(int32_t *)(i_v6 + 8)); // 0x10a58
    int32_t i_v12 = 4028;                                         // 0x10a60
    if (*p_v11 != 0) {
        // 0x10b28
        i_v12 = __asm_sxth(strtol(p_v11, NULL, 10));
    }
    // 0x10ae0
    return callapi(i_v8, i_v10, i_v12);
}

// Address range: 0x10b4c - 0x10b5c
int32_t function_10b4c(void) {
    // 0x10b4c
    int32_t i_v1; // 0x10b4c
    bool i_v2;    // 0x10b4c
    if (!i_v2) {
        i_v1 = function_44c718();
    }
    // 0x10b50
    if (!i_v2) {
        return i_v1;
    }
    int32_t i_v3 = i_v1; // 0x10b54
    if (!i_v2) {
        i_v3 = function_44c6e0();
    }
    // 0x10b58
    if (!i_v2) {
        __asm_svclt(0x4770);
    }
    return i_v3;
}

// Address range: 0x10b5c - 0x10b80
int32_t _start(int32_t i_a1, int32_t i_a2) {
    // 0x10b5c
    int32_t i_v1; // 0x10b5c
    __libc_start_main(0x109b8, i_a2, (char **)&i_v1, (void (*)())0x11071,
                      (void (*)())0x109b8, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x10b80 - 0x10b84
int32_t function_10b80(int32_t i_a1) {
    // 0x10b80
    return i_a1;
}

// Address range: 0x10b8c - 0x10ba8
int32_t function_10b8c(void) {
    // 0x10b8c
    if (i_g3 == 0) {
        int32_t i_v1; // 0x10b8c
        return i_v1;
    }
    // 0x10ba4
    __gmon_start__();
    return &i_g6;
}

// Address range: 0x10bb0 - 0x10c0c
int32_t function_10bb0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10bb0
    bool i_v1; // 0x10bb0
    if (i_v1) {
        return i_a1;
    }
    // 0x10be0
    int32_t i_v2;                   // 0x10bb0
    int32_t i_v3 = 0x100001 * i_v2; // 0x10be4
    bool i_v4;                      // 0x10bb0
    int32_t i_v5;                   // 0x10bb0
    if (i_v1) {
        // .thread
        i_v5 = i_v1 ? i_v3 : 0;
    } else {
        int32_t i_v6 = i_v3 & -1 - 0x400000 * i_v2; // 0x10be8
        i_v5 = i_v6 < 1 ? 0 : i_v3;
        i_v4 = i_v6 < 0;
        if (i_v6 == 0) {
            return unknown_240();
        }
    }
    // 0x10bf8
    if (i_v4 != i_v1) {
        __asm_svclt(0x4770);
    }
    float64_t f_v7; // 0x10bb0
    __asm_vqrshl_s8(f_v7, f_v7);
    __asm_vmvn_i32(0x40000);
    if (!i_v1) {
        *(int32_t *)i_a4 = i_v5;
    }
    return i_a1;
}

// Address range: 0x10c0c - 0x10c18
int32_t function_10c0c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    int32_t i_v1 = i_a1; // 0x10c0c
    if (i_a4 == 0) {
        // 0x10c0e
        i_v1 = function_10bb0(i_a1, i_a2, i_a3, 0);
        int32_t i_v2; // 0x10c0c
        *(char *)i_v2 = 1;
    }
    // 0x10c16
    return i_v1;
}

// Address range: 0x10c18 - 0x10c1a
int32_t function_10c18(void) {
    // 0x10c18
    int32_t i_v1; // 0x10c18
    return i_v1;
}

// Address range: 0x10c1c - 0x10c90
int32_t function_10c1c(int32_t i_a1) {
    int16_t **p_v1 = __ctype_b_loc(); // 0x10c24
    int32_t i_v2 = (int32_t)*p_v1;    // 0x10c2c
    uint32_t i_v3 = i_a1;             // 0x10c30
    while ((*(int16_t *)(2 * (int32_t) * (char *)i_v3 + i_v2) & 0x2000) != 0) {
        // 0x10c34
        i_v3++;
    }
    int32_t i_v4 = (int32_t)__rawmemchr((int32_t *)i_v3, 0); // 0x10c58
    if (i_v3 >= i_v4) {
        // 0x10c88
        return i_v3;
    }
    int32_t i_v5 = i_v4; // 0x10c64
    i_v5--;
    char *p_v6 = (char *)i_v5; // 0x10c64
    if ((*(int16_t *)(2 * (int32_t)*p_v6 + (int32_t)*p_v1) & 0x2000) != 0) {
        *p_v6 = 0;
    }
    while (i_v3 < i_v5) {
        // 0x10c64
        i_v5--;
        p_v6 = (char *)i_v5;
        if ((*(int16_t *)(2 * (int32_t)*p_v6 + (int32_t)*p_v1) & 0x2000) != 0) {
            *p_v6 = 0;
        }
    }
    // 0x10c88
    return i_v3;
}

// Address range: 0x10c90 - 0x10e20
int32_t display(int32_t i_a1) {
    // 0x10c90
    if (i_a1 == 0) {
        // 0x10e18
        return 0;
    }
    int32_t i_v1 = i_a1; // 0x10c9c
    int32_t i_v2;        // 0x10c90
    int32_t i_v3;        // 0x10c90
    int32_t i_v4;        // 0x10c90
    int32_t i_v5;        // 0x10c90
    int32_t i_v6;        // 0x10c90
    while (true) {
    lab_0x10ce0:
        // 0x10ce0
        i_v4 = i_v1;
        char *p_v7 = (char *)i_v4;      // 0x10ce8
        char *p_v8 = strchr(p_v7, 124); // 0x10ce8
        int32_t i_v9 = (int32_t)p_v8;   // 0x10ce8
        if (p_v8 == NULL) {
            // 0x10cf4
            i_v6 = i_v9;
            i_v3 = i_v9;
            if (*p_v7 == 0) {
                // break -> 0x10e18
                break;
            }
            goto lab_0x10d04;
        } else {
            int32_t i_v10 = i_v9 + 1; // 0x10cc4
            *p_v8 = 0;
            i_v2 = i_v9;
            i_v5 = i_v10;
            i_v6 = i_v10;
            if (*p_v7 == 0) {
                goto lab_0x10cd8;
            } else {
                goto lab_0x10d04;
            }
        }
    }
lab_0x10e18:
    // 0x10e18
    return i_v3;
lab_0x10d28:;
    // 0x10d28
    int32_t i_v11; // 0x10c90
    int32_t i_v12 = i_v11;
    char *p_v13;                     // 0x10c90
    char *p_v14 = strchr(p_v13, 61); // 0x10d30
    char *p_v15;                     // 0x10c90
    int32_t i_v16;                   // 0x10c90
    int32_t i_v17;                   // 0x10c90
    if (p_v14 == NULL) {
        if (i_v17 == 0) {
            // 0x10e04
            printf("[%s%s] =>\n(\n", p_v13, (char *)&p_g1);
            // 0x10de4
            printf("   [%d] => %s\n", i_v17, p_v13);
            i_v16 = i_v12;
            goto lab_0x10d9c;
        } else {
            // 0x10de4
            printf("   [%d] => %s\n", i_v17, p_v13);
            i_v16 = i_v12;
            goto lab_0x10d9c;
        }
    } else {
        // 0x10d3c
        *p_v14 = 0;
        int32_t i_v18 = (int32_t)p_v14 + 1; // 0x10d48
        if (i_v17 == 0) {
            if (i_v18 == 0) {
                // 0x10e04
                printf("[%s%s] =>\n(\n", p_v13, (char *)&p_g1);
                // 0x10de4
                printf("   [%d] => %s\n", i_v17, p_v13);
                i_v16 = i_v12;
                goto lab_0x10d9c;
            } else {
                int16_t **p_v19 = __ctype_b_loc(); // 0x10d58
                char *p_v20 = (char *)i_v18;
                int16_t i_v21 = *(int16_t *)(2 * (int32_t)*p_v20 +
                                             (int32_t)*p_v19); // 0x10d70
                printf("[%s%s] =>\n(\n", p_v13,
                       (i_v21 & 2048) == 0 ? (char *)&p_g1 : p_v20);
                p_v15 = p_v20;
                goto lab_0x10d84;
            }
        } else {
            if (i_v18 == 0) {
                // 0x10de4
                printf("   [%d] => %s\n", i_v17, p_v13);
                i_v16 = i_v12;
                goto lab_0x10d9c;
            } else {
                // 0x10ddc
                p_v15 = (char *)i_v18;
                goto lab_0x10d84;
            }
        }
    }
lab_0x10d9c:;
    int32_t i_v22 = i_v16;     // 0x10da4
    int32_t i_v23 = i_v17 + 1; // 0x10da4
    if (i_v16 == 0) {
        // break -> 0x10dcc
        goto lab_0x10dcc;
    }
    goto lab_0x10da8;
lab_0x10d84:
    // 0x10d84
    printf("   [%s] => %s\n", p_v13, p_v15);
    i_v16 = i_v12;
    goto lab_0x10d9c;
lab_0x10d04:
    // 0x10d04
    i_v22 = i_v4;
    i_v23 = 0;
    while (true) {
    lab_0x10da8:
        // 0x10da8
        i_v17 = i_v23;
        p_v13 = (char *)i_v22;
        char *p_v24 = strchr(p_v13, 44); // 0x10db0
        int32_t i_v25 = (int32_t)p_v24;  // 0x10db0
        if (p_v24 == NULL) {
            // 0x10dbc
            i_v11 = i_v25;
            if (*p_v13 == 0) {
                // break -> 0x10dcc
                break;
            }
            goto lab_0x10d28;
        } else {
            int32_t i_v26 = i_v25 + 1; // 0x10d10
            *p_v24 = 0;
            i_v11 = i_v26;
            i_v16 = i_v26;
            if (*p_v13 == 0) {
                goto lab_0x10d9c;
            } else {
                goto lab_0x10d28;
            }
        }
    }
lab_0x10dcc:
    // 0x10dcc
    i_v2 = puts(")");
    i_v5 = i_v6;
    goto lab_0x10cd8;
lab_0x10cd8:
    // 0x10cd8
    i_v1 = i_v5;
    i_v3 = i_v2;
    if (i_v1 == 0) {
        // break -> 0x10e18
        goto lab_0x10e18;
    }
    goto lab_0x10ce0;
}

// Address range: 0x10e20 - 0x11070
int32_t callapi(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    char *p_v1 = (char *)i_a2; // 0x10e38
    if (gethostbyname(p_v1) == NULL) {
        // 0x10f48
        printf("Couldn't get hostname: '%s'\n", p_v1);
        // 0x10f5c
        return 1;
    }
    int32_t i_v2 = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10e50
    if (i_v2 == -1) {
        // 0x10f68
        printf("Socket initialisation failed: %s\n",
               strerror(*__errno_location()));
        return 1;
    }
    // 0x10e60
    __asm_rev16(i_a3);
    int32_t i_v3 = 2; // bp-48, 0x10e84
    if (connect(i_v2, (struct sockaddr *)&i_v3, 16) < 0) {
        // 0x10f94
        printf("Socket connect failed: %s\n", strerror(*__errno_location()));
        return 1;
    }
    // 0x10ea8
    if (send(i_v2, (int32_t *)i_a1, strlen((char *)i_a1), 0) < 0) {
        // 0x11018
        printf("Send failed: %s\n", strerror(*__errno_location()));
        // 0x11004
        close(i_v2);
        return 1;
    }
    int32_t *p_v4 = malloc(0x10000); // 0x10ed0
    int32_t i_v5 = 0;                // 0x10ee0
    int32_t i_v6 = 0xffff;           // 0x10ee0
    int32_t *p_v7 = p_v4;            // 0x10ee0
    if (p_v4 == NULL) {
        // 0x11058
        printf("Err: OOM (%d)\n", 0x10000);
        // 0x10f5c
        return 1;
    }
    int32_t i_v8;   // 0x10e20
    int32_t i_v9;   // 0x10e20
    int32_t *p_v10; // 0x10e20
    int32_t i_v11;  // 0x10ee4
    while (true) {
        // 0x10ee4
        p_v10 = p_v7;
        i_v9 = (int32_t)p_v10;
        int32_t i_v12 = i_v5; // 0x10f00
        i_v11 = i_v12 + i_v9;
        int32_t i_v13 =
            recv(i_v2, (int32_t *)i_v11, i_v6 - i_v12, 0); // 0x10ef8
        if (i_v13 < 0) {
            // break (via goto) -> 0x10fc0
            goto lab_0x10fc0;
        }
        // 0x10f08
        i_v8 = 0;
        if (i_v13 == 0) {
            goto lab_0x10fe0;
        }
        // 0x10f0c
        i_v12 += i_v13;
        while (i_v6 != i_v12) {
            // 0x10ee4
            i_v11 = i_v12 + i_v9;
            i_v13 = recv(i_v2, (int32_t *)i_v11, i_v6 - i_v12, 0);
            if (i_v13 < 0) {
                // break (via goto) -> 0x10fc0
                goto lab_0x10fc0;
            }
            // 0x10f08
            i_v8 = 0;
            if (i_v13 == 0) {
                goto lab_0x10fe0;
            }
            // 0x10f0c
            i_v12 += i_v13;
        }
        int32_t i_v14 = i_v6 + 0x10000; // 0x10f14
        p_v7 = realloc(p_v10, i_v14);
        i_v5 = i_v6;
        int32_t i_v15; // 0x10e20
        i_v6 += (p_v4 == NULL ? i_v15 : 0xffff);
        if (p_v7 == NULL) {
            // 0x10f30
            printf("Err: OOM (%d)\n", i_v14);
            return 1;
        }
    }
lab_0x10fc0:
    // 0x10fc0
    printf("Recv failed: %s\n", strerror(*__errno_location()));
    i_v8 = 1;
lab_0x10fe0:
    // 0x10fe0
    *(char *)i_v11 = 0;
    if (i_g5 != 0) {
        // 0x10ffc
        puts((char *)p_v10);
        // 0x11004
        close(i_v2);
        return i_v8;
    }
    // 0x1103c
    printf("Reply was '%s'\n", p_v10);
    display(i_v9);
    // 0x11004
    close(i_v2);
    return i_v8;
}

// Address range: 0x11070 - 0x110a4
int32_t __libc_csu_init(int32_t i_a1, int32_t i_a2, int32_t i_a3,
                        int32_t i_a4) {
    int32_t i_v1 = _init(i_a1, i_a2, i_a3, i_a4); // 0x11080
    return 0x21f12 - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x110ac - 0x110ae
int32_t __libc_csu_fini(void) {
    // 0x110ac
    int32_t i_v1; // 0x110ac
    return i_v1;
}

// Address range: 0x110b0 - 0x110b8
int32_t _fini(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x110b0
    return i_a1;
}

// Address range: 0x44c6e0 - 0x44c6e1
int32_t function_44c6e0(void) {
    // 0x44c6e0
    int32_t i_v1; // 0x44c6e0
    return i_v1;
}

// Address range: 0x44c718 - 0x44c719
int32_t function_44c718(void) {
    // 0x44c718
    int32_t i_v1; // 0x44c718
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 39
